version: '3.8'

services:
  app:
    build: ./
    container_name: express_app
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - MONGO_URI=mongodb://mongo:27017/curso-node
    
  mongo:
    image: mongo:latest
    container_name: mongo_db
    restart: always
    ports:
      - "27018:27017"
    volumes:
      - mongo_data:/data/db

volumes: